/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
// This is a placeholder file. Run 'amplify init' and 'amplify push' to generate the real configuration.

const awsconfig = {
  Auth: {
    Cognito: {
      userPoolId: 'us-east-1_B5ijTwafm',
      userPoolClientId: '50t6absgkoc8j3suc107lvctb7',
      identityPoolId: 'us-east-1:0d5770be-c94f-4ae2-8183-3bd7e4ec791b',
      allowGuestAccess: true,
      loginWith: {
        email: true,
      },
      signUpVerificationMethod: 'code',
      userAttributes: {
        email: {
          required: true,
        },
      },
      passwordFormat: {
        minLength: 8,
        requireLowercase: true,
        requireUppercase: true,
        requireNumbers: true,
        requireSpecialCharacters: false,
      },
    },
  },
  Storage: {
    S3: {
      bucket: 'adam-hoggatt-portfolio-content',
      region: 'us-east-1',
    },
    // CloudFront CDN for fast public reads (PriceClass_100: US/Canada/Europe)
    cdnBase: 'https://d1hkp9aletiphg.cloudfront.net',
  },
};

export default awsconfig;
