/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
// This is a placeholder file. Run 'amplify init' and 'amplify push' to generate the real configuration.

const awsconfig = {
  Auth: {
    Cognito: {
      userPoolId: 'YOUR_USER_POOL_ID', // Replace after running 'amplify add auth'
      userPoolClientId: 'YOUR_WEB_CLIENT_ID', // Replace after running 'amplify add auth'
      identityPoolId: 'YOUR_IDENTITY_POOL_ID', // Replace after running 'amplify add auth'
      loginWith: {
        email: true,
      },
      signUpVerificationMethod: 'code',
      userAttributes: {
        email: {
          required: true,
        },
      },
      passwordFormat: {
        minLength: 8,
        requireLowercase: true,
        requireUppercase: true,
        requireNumbers: true,
        requireSpecialCharacters: true,
      },
    },
  },
  Storage: {
    S3: {
      bucket: 'YOUR_S3_BUCKET_NAME', // Replace after running 'amplify add storage'
      region: 'us-east-1', // Replace with your region
    },
  },
};

export default awsconfig;
